# Generated by Django 3.2.7 on 2021-09-25 04:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('otp_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='smsotpchallenge',
            index=models.Index(fields=['phone_number', 'secret'], name='otp_auth_sm_phone_n_572794_idx'),
        ),
    ]
