# Generated by Django 3.2.7 on 2021-11-28 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otp_auth', '0002_smsotpchallenge_otp_auth_sm_phone_n_572794_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smsotpchallenge',
            options={'verbose_name': 'SMS OTP Challenge', 'verbose_name_plural': 'SMS OTP Challenges'},
        ),
    ]
