# Generated by Django 3.2.7 on 2021-10-07 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregnancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('declared_pregnancy_week', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('declared_date_of_last_menstrual_period', models.DateField(blank=True, null=True)),
                ('declared_number_of_prenatal_visits', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('estimated_start_date', models.DateField()),
                ('estimated_delivery_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
