# Generated by Django 3.2.7 on 2021-10-09 04:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child_health', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregnancy',
            name='declared_pregnancy_week',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(42)]),
        ),
    ]
