# Generated by Django 3.2.7 on 2021-10-10 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child_health', '0002_alter_pregnancy_declared_pregnancy_week'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pregnancy',
            index=models.Index(fields=['user'], name='child_healt_user_id_2424d4_idx'),
        ),
        migrations.AddIndex(
            model_name='pregnancy',
            index=models.Index(fields=['estimated_delivery_date'], name='child_healt_estimat_3bd12e_idx'),
        ),
    ]
