# Generated by Django 3.2.7 on 2021-10-10 03:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('child_health', '0004_auto_20211010_0209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('nickname', models.CharField(max_length=100)),
                ('applicable_for_male', models.BooleanField(default=True)),
                ('applicable_for_female', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='child',
            options={'verbose_name_plural': 'Children'},
        ),
        migrations.AddField(
            model_name='child',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='child',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='VaccineDose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('week_age', models.PositiveSmallIntegerField()),
                ('notes_for_parent', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='child_health.vaccine')),
            ],
        ),
        migrations.AddIndex(
            model_name='vaccinedose',
            index=models.Index(fields=['week_age'], name='child_healt_week_ag_f2a189_idx'),
        ),
        migrations.AddIndex(
            model_name='vaccinedose',
            index=models.Index(fields=['vaccine'], name='child_healt_vaccine_4f8352_idx'),
        ),
    ]
