# Generated by Django 3.2.7 on 2021-10-10 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('child_health', '0005_auto_20211010_0333'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastVaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='child_health.child')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='child_health.vaccine')),
            ],
        ),
        migrations.AddField(
            model_name='child',
            name='past_vaccinations',
            field=models.ManyToManyField(through='child_health.PastVaccination', to='child_health.Vaccine'),
        ),
        migrations.AddIndex(
            model_name='pastvaccination',
            index=models.Index(fields=['child'], name='child_healt_child_i_35a2c1_idx'),
        ),
        migrations.AddIndex(
            model_name='pastvaccination',
            index=models.Index(fields=['vaccine'], name='child_healt_vaccine_eb9f28_idx'),
        ),
    ]
