# Generated by Django 3.2.7 on 2021-10-10 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child_health', '0006_auto_20211010_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
