# Generated by Django 3.2.7 on 2021-10-10 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child_health', '0007_alter_vaccine_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinedose',
            name='notes_for_parent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
