# Generated by Django 3.2.7 on 2021-10-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child_health', '0008_alter_vaccinedose_notes_for_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccine',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
