# Generated by Django 3.2.7 on 2021-11-28 15:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child_health', '0010_alter_child_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregnancy',
            name='declared_number_of_prenatal_visits',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name='pregnancy',
            name='declared_pregnancy_week',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(42)]),
        ),
    ]
