# Generated by Django 4.0 on 2022-01-09 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('child_health', '0011_auto_20211128_1523'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pregnancy',
            options={'verbose_name_plural': 'Pregnancies'},
        ),
    ]
