# Generated by Django 4.0.1 on 2022-01-29 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('child_health', '0012_alter_pregnancy_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pastvaccination',
            unique_together={('child', 'vaccine')},
        ),
    ]
