# Generated by Django 3.2.7 on 2021-09-25 09:12

import datetime

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False,
                                      to='auth.user')),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=20)),
                ('date_of_birth',
                 models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2021, 9, 25))])),
                ('agree_to_terms_at', models.DateTimeField()),
            ],
        ),
    ]
