# Generated by Django 3.2.7 on 2021-12-02 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user_profile', '0003_phonenumberchangerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingProgress',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('has_filled_profile', models.BooleanField(default=False, help_text="Whether the user has submitted or skipped 'Complete Profile' onboarding screen")),
                ('has_filled_pregnancy_status', models.BooleanField(default=False, help_text="Whether the user has submitted or skipped 'Your Pregnancy' onboarding screen")),
                ('has_filled_children_info', models.BooleanField(default=False, help_text="Whether the user has submitted or skipped 'Children Info' onboarding screen")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
