# Generated by Django 3.2.9 on 2021-12-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_onboardingprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='language_code',
            field=models.CharField(choices=[('en', 'English'), ('tr', 'Turkish'), ('ar', 'Arabic')], default='en', max_length=5),
        ),
    ]
