# Generated by Django 4.0.1 on 2022-01-16 10:05

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='survey',
            new_name='survey_template',
        ),
        migrations.RemoveField(
            model_name='surveytemplate',
            name='name',
        ),
        migrations.RemoveField(
            model_name='surveytemplate',
            name='options',
        ),
        migrations.RemoveField(
            model_name='surveytemplate',
            name='question',
        ),
        migrations.RemoveField(
            model_name='surveytemplate',
            name='user',
        ),
        migrations.AddField(
            model_name='survey',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='event_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='expires_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='surveytemplate',
            name='code',
            field=models.CharField(default='auto-generated-code', help_text='Alphanumeric code you can send to the devs to let them trigger this survey on certain condition.', max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator(' ', 'No spaces allowed', inverse_match=True), django.core.validators.RegexValidator('[A-Z]', 'No UPPERCASE allowed', inverse_match=True), django.core.validators.RegexValidator('^[a-z1-9._]+$', 'Only lowercase character, number, . and _ allowed')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surveytemplate',
            name='description',
            field=models.CharField(default='', help_text='When is this survey sent? What is the purpose of this survey? Note for translators & devs?', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.survey'),
        ),
        migrations.AlterField(
            model_name='surveytemplate',
            name='survey_type',
            field=models.CharField(choices=[('MULTIPLE_CHOICE', 'Multiple Choice'), ('TEXT', 'Text')], max_length=255),
        ),
        migrations.CreateModel(
            name='SurveyTemplateOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(' ', 'No spaces allowed', inverse_match=True), django.core.validators.RegexValidator('[A-Z]', 'No UPPERCASE allowed', inverse_match=True), django.core.validators.RegexValidator('^[a-z1-9._]+$', 'Only lowercase character, number, . and _ allowed')])),
                ('option_en', models.CharField(max_length=50, verbose_name='Option in English')),
                ('option_tr', models.CharField(blank=True, max_length=50, null=True, verbose_name='Option in Turkish')),
                ('option_ar', models.CharField(blank=True, max_length=50, null=True, verbose_name='Option in Arabic')),
                ('survey_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.surveytemplate')),
            ],
        ),
        migrations.CreateModel(
            name='SurveySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_event_type', models.CharField(choices=[('prenatal_checkup', 'Prenatal Checkup'), ('vaccination', 'Vaccination')], max_length=50)),
                ('offset_days', models.SmallIntegerField()),
                ('time_of_day', models.TimeField()),
                ('time_to_live', models.DurationField(default=datetime.timedelta(days=7), help_text='(days hh:mm:ss) If this amount of time has passed after the calendar event, no survey will be generated.', validators=[django.core.validators.MinValueValidator(datetime.timedelta(seconds=3600))], verbose_name='Duration until survey expires')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('survey_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.surveytemplate')),
            ],
        ),
        migrations.AddField(
            model_name='survey',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='surveys.surveyschedule'),
        ),
        migrations.AlterUniqueTogether(
            name='survey',
            unique_together={('event_key', 'schedule')},
        ),
        migrations.CreateModel(
            name='SurveyTemplateTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(choices=[('en', 'English'), ('tr', 'Turkish'), ('ar', 'Arabic')], max_length=5)),
                ('question', models.CharField(help_text='Question to be shown in the survey pop-up in app', max_length=255)),
                ('survey_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.surveytemplate')),
            ],
            options={
                'unique_together': {('survey_template', 'language_code')},
            },
        ),
        migrations.RemoveField(
            model_name='survey',
            name='date_created',
        ),
    ]
