# Generated by Django 4.0.1 on 2022-01-17 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_rename_survey_survey_survey_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='response',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='SurveyResponse',
        ),
    ]
