# Generated by Django 4.0.1 on 2022-01-23 09:19

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_survey_available_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='context',
            field=django.contrib.postgres.fields.hstore.HStoreField(default=dict),
        ),
    ]
