# Generated by Django 4.0.1 on 2022-01-29 12:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('surveys', '0005_survey_context'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='survey',
            index_together={('user', 'response')},
        ),
    ]
