# Generated by Django 4.0.3 on 2022-04-25 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0007_alter_surveytemplatetranslation_language_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveytemplateoption',
            name='option_ars',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Option in Dari'),
        ),
        migrations.AddField(
            model_name='surveytemplateoption',
            name='option_ps',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Option in Pashto'),
        ),
    ]
