# Generated by Django 4.0.4 on 2022-05-24 14:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0008_surveytemplateoption_option_ars_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveytemplate',
            name='code',
            field=models.CharField(help_text='Alphanumeric code you can send to the devs to let them trigger this survey on certain condition.', max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator(' ', 'No spaces allowed', inverse_match=True), django.core.validators.RegexValidator('[A-Z]', 'No UPPERCASE allowed', inverse_match=True), django.core.validators.RegexValidator('^[a-z0-9._]+$', 'Only lowercase character, number, . and _ allowed')]),
        ),
        migrations.AlterField(
            model_name='surveytemplateoption',
            name='code',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(' ', 'No spaces allowed', inverse_match=True), django.core.validators.RegexValidator('[A-Z]', 'No UPPERCASE allowed', inverse_match=True), django.core.validators.RegexValidator('^[a-z0-9._]+$', 'Only lowercase character, number, . and _ allowed')]),
        ),
    ]
