# Generated by Django 3.2.7 on 2021-12-05 09:31

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Alphanumeric code you can send to the devs to let them trigger this notification on certain condition.', max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator('[A-Z1-9._]+')])),
                ('description', models.CharField(help_text='When is this notification sent? What is the purpose of this notification? Note for translators & devs?', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationTemplateVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the variable. Can be used in template, e.g. {{ variable_name }}.', max_length=50)),
                ('example_values', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), help_text='Some example values of this variable', size=None)),
                ('description', models.CharField(help_text='What does this variable mean?', max_length=1000)),
                ('notification_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.notificationtype')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(choices=[('en', 'English'), ('tr', 'Turkish'), ('ar', 'Arabic')], max_length=5)),
                ('push_title', models.CharField(help_text='Title to be shown in push notification (shown in Android / iOS notification centre and lock screen)', max_length=100)),
                ('push_body', models.CharField(help_text='Body to be shown in push notification (shown in Android / iOS notification centre and lock screen)', max_length=255)),
                ('in_app_content', models.CharField(help_text='Text to be shown inside HERA app notification screen.', max_length=1000)),
                ('notification_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.notificationtype')),
            ],
            options={
                'unique_together': {('notification_type', 'language_code')},
            },
        ),
    ]
