# Generated by Django 3.2.9 on 2021-12-11 16:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_notificationtemplate_notificationtemplatevariable_notificationtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtemplatevariable',
            name='name',
            field=models.CharField(help_text='The name of the variable. Can be used in template, e.g. {{ variable_name }}.', max_length=50, validators=[django.core.validators.RegexValidator(' ', 'No spaces allowed', inverse_match=True), django.core.validators.RegexValidator('[A-Z]', 'No UPPERCASE allowed', inverse_match=True), django.core.validators.RegexValidator('^[a-z1-9._]+$', 'Only lowercase character, number, . and _ allowed')]),
        ),
        migrations.AlterField(
            model_name='notificationtype',
            name='code',
            field=models.CharField(help_text='Alphanumeric code you can send to the devs to let them trigger this notification on certain condition.', max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator(' ', 'No spaces allowed', inverse_match=True), django.core.validators.RegexValidator('[A-Z]', 'No UPPERCASE allowed', inverse_match=True), django.core.validators.RegexValidator('^[a-z1-9._]+$', 'Only lowercase character, number, . and _ allowed')]),
        ),
    ]
