# Generated by Django 3.2.9 on 2021-12-17 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20211217_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationevent',
            name='read_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
