# Generated by Django 3.2.9 on 2021-12-21 07:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_notificationevent_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationschedule',
            name='push_time_to_live',
            field=models.DurationField(default=datetime.timedelta(days=1), help_text='(days hh:mm:ss) If this amount of time has passed after the calendar event, no notification will be generated. '),
        ),
    ]
