# Generated by Django 4.0.3 on 2022-03-20 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_alter_notificationschedule_notification_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtemplate',
            name='language_code',
            field=models.CharField(choices=[('en', 'English'), ('tr', 'Turkish'), ('ar', 'Arabic'), ('ps', 'Pashto'), ('prs', 'Dari')], max_length=5),
        ),
    ]
