# Generated by Django 4.0.3 on 2022-03-26 08:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_alter_notificationtemplate_language_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstantNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_numbers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=15), size=15)),
            ],
        ),
    ]
