# Generated by Django 4.0.3 on 2022-03-26 10:15

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_instantnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='instantnotification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instantnotification',
            name='notification_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.notificationtype'),
        ),
        migrations.AddField(
            model_name='instantnotification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='instantnotification',
            name='phone_numbers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), size=15),
        ),
    ]
