# Generated by Django 4.0.3 on 2022-03-26 10:40

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_instantnotification_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instantnotification',
            name='notification_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.notificationtype'),
        ),
        migrations.AlterField(
            model_name='instantnotification',
            name='phone_numbers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), size=None),
        ),
    ]
